# Generated by Django 5.0.4 on 2024-04-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('source_url', models.URLField()),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('translate_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_age', models.IntegerField()),
                ('source_url', models.URLField()),
                ('title', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('original_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles_api.rawarticle')),
            ],
        ),
    ]
